lsst/templates

- project_templates/technote_latex/CHANGELOG.md
- project_templates/technote_latex/README.md
- project_templates/technote_latex/cookiecutter.json
- project_templates/technote_latex/templatekit.yaml
- project_templates/technote_rst/CHANGELOG.md
- project_templates/technote_rst/README.md
- project_templates/technote_rst/cookiecutter.json
- project_templates/technote_rst/templatekit.yaml
This technote series is requested by LSST IT and is hosted out of their https://github.com/LSST-IT organization
> Add the ITTN technote series

- project_templates/technote_aastex/README.md
- project_templates/technote_aastex/SConscript
- project_templates/technote_aastex/cookiecutter.json
- project_templates/technote_aastex/templatekit.yaml
- project_templates/technote_aastex/testn-000/.travis.yml
- project_templates/technote_aastex/testn-000/Makefile
- project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.travis.yml
- project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/Makefile
- project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/authors.yaml
Fixes items that were identified in the review for #45 but were not fixed. Also fixes the Travis-based build, including fixing the invocation of db2authors.py
I still can't get bibtex references to resolve; that'll have to be addressed in a future PR.
> DM-21378: technote_aastex improvements for production

- project_templates/technote_aastex/testn-000/appendix.tex
This adds a file that was missed in #49. Note that #51, still in development, will prevent these types of fo errors in the future.
> Add example appendix.tex file

- project_templates/technote_rst/CHANGELOG.md
- project_templates/technote_rst/templatekit.yaml
The value in templatekit.yaml needs to match the series array in cookiecutter.json
> DM-21842: Fix TSTN support

- file_templates/copyright/CHANGELOG.md
- file_templates/copyright/COPYRIGHT
- file_templates/copyright/cookiecutter.json
- project_templates/stack_package/CHANGELOG.md
- project_templates/stack_package/cookiecutter.json
- project_templates/stack_package/example/COPYRIGHT
- project_templates/stack_package/example_dataonly/COPYRIGHT
- project_templates/stack_package/example_dds/COPYRIGHT
- project_templates/stack_package/example_pythononly/COPYRIGHT
- project_templates/stack_package/example_standalone/COPYRIGHT
- project_templates/stack_package/example_subpackage/COPYRIGHT
- project_templates/technote_aastex/CHANGELOG.md
- project_templates/technote_aastex/cookiecutter.json
- project_templates/technote_aastex/testn-000/COPYRIGHT
- project_templates/technote_latex/CHANGELOG.md
- project_templates/technote_latex/cookiecutter.json
- project_templates/technote_latex/testn-000/COPYRIGHT
- project_templates/technote_rst/cookiecutter.json
- project_templates/technote_rst/testn-000/COPYRIGHT
- project_templates/technote_rst/testn-000/metadata.yaml
This is the form recommended by lawyers from Gemini.
Updates:
- `copyright`
- `stack_package`
- `technote_aastex`
- `technote_latex`
- `technote_rst`
> DM-22101: Update AURA copyright to include "Inc. (AURA)"

- project_templates/stack_package/CHANGELOG.md
- project_templates/stack_package/example/setup.cfg
- project_templates/stack_package/example_dds/setup.cfg
- project_templates/stack_package/example_pythononly/setup.cfg
- project_templates/stack_package/example_standalone/setup.cfg
- project_templates/stack_package/example_subpackage/setup.cfg
- project_templates/stack_package/{{cookiecutter.package_name}}/setup.cfg
This change is related to the adoption of RFC-650 (https://jira.lsstcorp.org/browse/RFC-650).
> DM-23181: Replace W504 with W503

- project_templates/roundtable_aiohttp_bot/example/src/example/cli.py
- project_templates/roundtable_aiohttp_bot/example/src/example/handlers/__init__.py
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/src/{{cookiecutter.package_name}}/cli.py
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/src/{{cookiecutter.package_name}}/handlers/__init__.py
- Improve `help` error handling (and remove a mypy `# type: ignore`)
- Markup tweaks to handler documentation
> roundtable_aiohttp_bot template improvements

- project_templates/roundtable_aiohttp_bot/example/pyproject.toml
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/pyproject.toml
- Add `__init__.py` files to `tests`
- Tell isort to add trailing commas to multi-line imports so that it doesn't fight with black
- Make indents consistent in `pyproject.toml`
- Add tests to known first-party module prefixes for isort
> roundtable_aiohttp_bot template updates

- project_templates/roundtable_aiohttp_bot/example/scripts/install-base-packages.sh
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/install-base-packages.sh
Helps with debugging things in GitHub.
> Use set -x in install-base-packages.sh

- project_templates/roundtable_aiohttp_bot/example/src/example/__init__.py
- project_templates/roundtable_aiohttp_bot/example/src/example/app.py
- project_templates/roundtable_aiohttp_bot/example/src/example/handlers/__init__.py
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/__init__.py
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/app.py
- project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/handlers/__init__.py
Fixes some minor issues:
- extra symbols in `__all__`
- typos in docstrings.
> DM-27028: Fixes to roundtable_aiohttp_bot template

- project_templates/latex_lsstdoc/EXAMPLE-0/Makefile
- project_templates/latex_lsstdoc/EXAMPLE/Makefile
- project_templates/latex_lsstdoc/{{cookiecutter.handle}}/Makefile
- project_templates/technote_latex/testn-000/Makefile
- project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/Makefile
- project_templates/test_report/TESTTR-0/Makefile
- project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/Makefile
very small change -- I think its big sur but make now executes using /bin/sh and echo '\n' does not behave as it used to .. no problem for the github actions .. only on local use
> More robust printf than echo

- file_templates/copyright/COPYRIGHT
- project_templates/latex_lsstdoc/EXAMPLE-0/.github/workflows/ci.yaml
- project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
- project_templates/latex_lsstdoc/EXAMPLE/.github/workflows/ci.yaml
- project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
- project_templates/latex_lsstdoc/{{cookiecutter.handle}}/.github/workflows/ci.yaml
- project_templates/stack_package/example/COPYRIGHT
- project_templates/stack_package/example_dataonly/COPYRIGHT
- project_templates/stack_package/example_dds/COPYRIGHT
- project_templates/stack_package/example_pythononly/COPYRIGHT
- project_templates/stack_package/example_standalone/COPYRIGHT
- project_templates/stack_package/example_subpackage/COPYRIGHT
- project_templates/technote_aastex/testn-000/.github/workflows/ci.yaml
- project_templates/technote_aastex/testn-000/COPYRIGHT
- project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
- project_templates/technote_latex/testn-000/.github/workflows/ci.yaml
- project_templates/technote_latex/testn-000/COPYRIGHT
- project_templates/technote_latex/testn-000/bibentry.txt
- project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
- project_templates/technote_rst/testn-000/.github/workflows/ci.yaml
- project_templates/technote_rst/testn-000/COPYRIGHT
- project_templates/technote_rst/testn-000/bibentry.txt
- project_templates/technote_rst/testn-000/metadata.yaml
- project_templates/technote_rst/{{cookiecutter.repo_name}}/.github/workflows/ci.yaml
- project_templates/test_report/TESTTR-0/.github/workflows/ci.yaml
- project_templates/test_report/TESTTR-0/bibentry.txt
- project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
This prevents rate limiting issues the docker image pulls.
> DM-28655: Add docker/login-action to LaTeX document builds

- CONTRIBUTING.md
We're now running tests on GitHub Actins.
> Update CONTRIBUTING guide to refer to GitHub Actions

- project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
- project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
- project_templates/latex_lsstdoc/{{cookiecutter.handle}}/bibentry.txt
- project_templates/stack_package/example/.github/workflows/lint.yaml
- project_templates/stack_package/example_dds/.github/workflows/lint.yaml
- project_templates/stack_package/example_pythononly/.github/workflows/lint.yaml
- project_templates/stack_package/example_standalone/.github/workflows/lint.yaml
- project_templates/stack_package/example_subpackage/.github/workflows/lint.yaml
- project_templates/stack_package/{{cookiecutter.package_name}}/.github/workflows/lint.yaml
- project_templates/technote_aastex/README.md
- project_templates/technote_latex/CHANGELOG.md
- project_templates/technote_latex/README.md
- project_templates/technote_latex/testn-000/bibentry.txt
- project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/bibentry.txt
- project_templates/technote_rst/testn-000/README.rst
- project_templates/technote_rst/testn-000/bibentry.txt
- project_templates/technote_rst/testn-000/index.rst
- project_templates/technote_rst/testn-000/lsstbib/README.md
- project_templates/technote_rst/{{cookiecutter.repo_name}}/README.rst
- project_templates/technote_rst/{{cookiecutter.repo_name}}/bibentry.txt
- project_templates/technote_rst/{{cookiecutter.repo_name}}/index.rst
- project_templates/technote_rst/{{cookiecutter.repo_name}}/lsstbib/README.md
- project_templates/test_report/TESTTR-0/bibentry.txt
- project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/bibentry.txt
But not for SQuaRE repos/projects.
> DM-32648: Change default branch to main.

- project_templates/test_report/README.md
> Fix typo in link generation in the README for test reports

- project_templates/fastapi_safir_app/example/Dockerfile
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile
Update the Python base image used in the FastAPI project
template.
> Update Python base image for FastAPI

- project_templates/sitcom_personal_notebooks/templatekit.yaml
The max length allowed by Slack is 25 characters.
> DM-34274: Shorten the dialog title for sitcom notebooks repo template

- README.md
These should match the intent of their contents links now
> Update headers for templates

- project_templates/fastapi_safir_app/example/.pre-commit-config.yaml
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/.pre-commit-config.yaml
The version here doesn't work out of the box, there is a problem
with the dependencies, and this version fixes that.
https://github.com/psf/black/issues/2964
> [DM-34552] Use black 22.3.0

- .github/workflows/ci.yaml
- project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
Bump the versions of all of the actions used by the Docker build
rules for the FastAPI template.
> [DM-34744] Bump GitHub Actions Docker action versions

- SConstruct
> Delete call to aiohttp_bot SConscript

- project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
- project_templates/fastapi_safir_app/example/Dockerfile
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile
Update the Python base image to the latest version and update the
setup-python action to v4.
> Update FastAPI Safir template dependencies

- project_templates/fastapi_safir_app/example/.pre-commit-config.yaml
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/.pre-commit-config.yaml
- project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
- project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
- project_templates/square_pypi_package/example/.pre-commit-config.yaml
- project_templates/square_pypi_package/{{cookiecutter.pypi_name}}/.pre-commit-config.yaml
- project_templates/technote_latex/testn-000/bibentry.txt
- project_templates/technote_rst/testn-000/bibentry.txt
- project_templates/test_report/TESTTR-0/bibentry.txt
Fix the URL for flake8.  Fix capitalization for PyCQA URLs.  Add
the trailing-whitespace hook to the fastapi_safir_app checks.  Make
formatting consistent with the squre_pypi_package lints.
> Update pre-commit configuration

- project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
- project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
- project_templates/square_pypi_package/example/.github/workflows/ci.yaml
- project_templates/square_pypi_package/{{cookiecutter.name}}/.github/workflows/ci.yaml
The name of the GitHub Actions trigger is merge_group, not merge_request.
> DM-38414: Fix merge queue support

- project_templates/technote_md_early_adopter/testn-000/index.md
- project_templates/technote_md_early_adopter/testn-000/technote.toml
- project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/index.md
- project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/technote.toml
- project_templates/technote_rst_early_adopter/testn-000/technote.toml
- project_templates/technote_rst_early_adopter/{{cookiecutter.repo_name}}/technote.toml
- Fix abstract directive in markdown.
- Fix name keys in technote.toml.
> DM-41781: Fix early adopter technote templates

- project_templates/technote_spietex/testn-000/TESTN-000.tex
- project_templates/technote_spietex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}.tex
> \maketitle missing in spie template

- project_templates/technote_spietex/testn-000/TESTN-000.tex
- project_templates/technote_spietex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}.tex
* Remove today's date
* Remove appendix
* Remove acronyms
> Put acknowledgments in right place in SPIE and other cleanups
