.gitignore
.travis.yml
CONTRIBUTING.md
README.md
SConstruct
file_templates/stack_license_cpp/SConscript
file_templates/stack_license_cpp/cookiecutter.json
file_templates/stack_license_cpp/example.cc
file_templates/stack_license_f90/SConscript
file_templates/stack_license_f90/cookiecutter.json
file_templates/stack_license_f90/example.f90
file_templates/stack_license_py/SConscript
file_templates/stack_license_py/cookiecutter.json
file_templates/stack_license_py/example.py
file_templates/stack_license_py/template.py.jinja
project_templates/example_project/README.md
project_templates/example_project/SConscript
project_templates/example_project/cookiecutter.json
project_templates/example_project/example/demo_file.rst
project_templates/example_project/{{cookiecutter.project_name}}/{{cookiecutter.file_name}}.rst
setup.cfg
setup.py
templatekit/builder.py
templatekit/filerender.py
tests/test_filerender.py

This PR enables automatic testing of the templates. Essentially, we run cookiecutter on every file and project template and ensure that the Git state is clean after doing so to ensure that the committed examples are up to date. Testing is done with Travis.
The core changes are:
- A central SConstruct file to regenerate all examples, which. delegates to the SConscript files of individual templates.
- A templatekit Python package that provides custom Scons builders for the cookiecutter templates. One of the key accomplishments here is demonstrating that cookiecutter's APIs can let us render single file templates.
- Documentation for the template CI system and SConscript files.

DM-11699: system for building and testing template examples

---

project_templates/stack_package/example/doc/lsst.example/index.rst
project_templates/stack_package/example_pythononly/doc/lsst.example.pythononly/index.rst
project_templates/stack_package/example_subpackage/doc/lsst.example.subpackage/index.rst
project_templates/stack_package/{{cookiecutter.package_name}}/doc/{{cookiecutter.python_module}}/index.rst

The `py:currentmodule` directive enables writers to refer to APIs without specifying the full namespace.
*Note: content changes in `example*/` directories are all auto-generated but do demo the outcomes of the template change.*

DM-14076: Add currentmodule directive to module doc page in stack_package template

---

project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/example/ups/example.table
project_templates/stack_package/example_pythononly/ups/example_pythononly.table
project_templates/stack_package/example_subpackage/ups/example_subpackage.table
project_templates/stack_package/{{cookiecutter.package_name}}/ups/{{cookiecutter.package_name}}.table

- Version pinning isn't used anymore since packages are always tagged together.
- Modernize comments in table file.

DM-14668: Remove version pinning from stack_package table file

---

project_templates/stack_package/example_pythononly/SConstruct
project_templates/stack_package/{{cookiecutter.package_name}}/SConstruct

This BasicSConstruct flag makes it easier to develop pure-python packages without needing cc compilers during build time.

DM-14860: Add disableCc=True flag when uses_cpp is False

---

project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/README.md
project_templates/stack_package/example/doc/lsst.example/index.rst
project_templates/stack_package/example/setup.cfg
project_templates/stack_package/example/tests/SConscript
project_templates/stack_package/example/ups/example.build
project_templates/stack_package/example_dataonly/ups/example_dataonly.build
project_templates/stack_package/example_pythononly/doc/lsst.example.pythononly/index.rst
project_templates/stack_package/example_pythononly/setup.cfg
project_templates/stack_package/example_pythononly/tests/SConscript
project_templates/stack_package/example_pythononly/ups/example_pythononly.build
project_templates/stack_package/example_subpackage/doc/lsst.example.subpackage/index.rst
project_templates/stack_package/example_subpackage/setup.cfg
project_templates/stack_package/example_subpackage/tests/SConscript
project_templates/stack_package/example_subpackage/ups/example_subpackage.build
project_templates/stack_package/{{cookiecutter.package_name}}/doc/{{cookiecutter.python_module}}/index.rst
project_templates/stack_package/{{cookiecutter.package_name}}/setup.cfg
project_templates/stack_package/{{cookiecutter.package_name}}/tests/SConscript
project_templates/stack_package/{{cookiecutter.package_name}}/ups/{{cookiecutter.package_name}}.build

- Deleted the `ups/*.build` file.
It turns out that this file is not used by the build system.
- Added `pyList` argument to the `tests/Sconscript` file.
This enables auto file detection.
- Updated the `setup.cfg` configuration file.
This adds the N806 flake8 exception and the `[tool:pytest]` section.
- Updated the default `automodapi` usage in module documenation homepages.
- `no-main-docstr` is something we always want to use since the main docstring in `__init__.py` shouldn't be used, in favour of writing topics in the `doc/` directory.
- Most modules don't have interesting class inheritance, so it makes sense to default to `no-inheritance-diagram`.

DM-15110: Various updates to the stack_package template

---

project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/example/setup.cfg
project_templates/stack_package/example_pythononly/setup.cfg
project_templates/stack_package/example_subpackage/setup.cfg
project_templates/stack_package/{{cookiecutter.package_name}}/setup.cfg

The E251 rule exception is no longer included in `setup.cfg` since it is also not adopted by the [Python style guide](https://developer.lsst.io/python/style.html#exceptions-to-pep-8).
Implements #19

DM-16040: Remove unnecessary condition E251

---

file_templates/task_topic/lsst.example.ExampleCmdLineTask.rst
file_templates/task_topic/lsst.example.ExampleTask.rst
file_templates/task_topic/{{cookiecutter.task_module}}.{{cookiecutter.task_class}}.rst.jinja

This will ensure that labels are unique even if there is a class name collision.

DM-15422: Labels in task topic use full namespace

---

project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/example/.gitignore
project_templates/stack_package/example/setup.cfg
project_templates/stack_package/example/ups/example.table
project_templates/stack_package/example_dataonly/.gitignore
project_templates/stack_package/example_dataonly/ups/example_dataonly.table
project_templates/stack_package/example_pythononly/.gitignore
project_templates/stack_package/example_pythononly/setup.cfg
project_templates/stack_package/example_pythononly/ups/example_pythononly.table
project_templates/stack_package/example_subpackage/.gitignore
project_templates/stack_package/example_subpackage/setup.cfg
project_templates/stack_package/example_subpackage/ups/example_subpackage.table
project_templates/stack_package/{{cookiecutter.package_name}}/.gitignore
project_templates/stack_package/{{cookiecutter.package_name}}/setup.cfg
project_templates/stack_package/{{cookiecutter.package_name}}/ups/{{cookiecutter.package_name}}.table

- Added `bin/` and `.coverage` to `.gitignore`.
- Added `base` as a default EUPS dependency. This prevents packages that have not other dependencies from having errors about getting `lsstimport`.
Packages that add high-level dependencies can drop the explicit dependency on `base`.
- Also add `utils` as a default EUPS dependency since it is necessary for unit tests.
- Marked W504 (line break after binary operator) as an ignored Flake8 rule. This rule was introduced by pycodestyle 2.4.0, but is not part of the [DM Python Style Guide](https://developer.lsst.io/python/style.html). See the post [Changes to baseline software versions](https://community.lsst.org/t/changes-to-baseline-software-versions/3366).

DM-16437: Stack package updates (base and utils dependencies, W504, gitignores)

---

setup.py

This update is needed to avoid flake8 incompatibility issues with the previously pinned test dependencies.

Update pytest to 4.2 and pytest-flake8

---

project_templates/technote_latex/testn-000/Makefile
project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/Makefile

- Use ?= so the user can override on the command line if necessary.
- Need to use `export` or it isn't picked up by xelatex.

Correct TEXMFHOME setting in Makefile.

---

README.md
SConstruct
file_templates/argparse_script_topic/README.md
file_templates/argparse_script_topic/SConscript
file_templates/argparse_script_topic/cookiecutter.json
file_templates/argparse_script_topic/exampleScript.py.rst
file_templates/argparse_script_topic/templatekit.yaml
file_templates/argparse_script_topic/{{cookiecutter.script_name}}.rst.jinja
file_templates/script_topic/README.md
file_templates/script_topic/SConscript
file_templates/script_topic/cookiecutter.json
file_templates/script_topic/exampleScript.sh.rst
file_templates/script_topic/templatekit.yaml
file_templates/script_topic/{{cookiecutter.script_name}}.rst.jinja
project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/example/doc/lsst.example/index.rst
project_templates/stack_package/example_pythononly/doc/lsst.example.pythononly/index.rst
project_templates/stack_package/example_standalone/doc/index.rst
project_templates/stack_package/example_subpackage/doc/lsst.example.subpackage/index.rst
project_templates/stack_package/{{cookiecutter.package_name}}/doc/{{cookiecutter.python_module}}/index.rst

- `script_topic` is for documenting any kind of script, but manually.
- `argparse_script_topic` is for documenting argparse-based Python scripts.
- The module homepage template for stack pages now has a "Script reference" section.
This system for documenting scripts is demonstrated in lsst/verify/pull/45 and is also documented in lsst-dm/dm_dev_guide/pull/339

DM-20821: New templates for documenting scripts

---

file_templates/argparse_script_topic/templatekit.yaml
file_templates/script_topic/templatekit.yaml

- Wrong cookiecutter.json key for argparse_script_topic
- The script_name is not optional

DM-20821: Fix templatekit config for script templates

---

project_templates/technote_latex/CHANGELOG.md
project_templates/technote_latex/testn-000/Makefile
project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/Makefile

This improves the initial experience of starting a new latex document where running bibtex would fail because the document didn't have any citations yet.

DM-20952: Adopt latexmk for the PDF build

---

file_templates/task_topic/lsst.example.ExampleCmdLineTask.rst
file_templates/task_topic/lsst.example.ExampleTask.rst
file_templates/task_topic/{{cookiecutter.task_module}}.{{cookiecutter.task_class}}.rst.jinja

This fixes the templating for the arguments to the `lsst-task-config-fields` and `lsst-task-config-subtasks` configuration fields.
This change automatically gets propagated to the Developer Guide: https://developer.lsst.io/stack/task-topic-type.html

DM-20692: Fix templating for subtasks and fields

---

project_templates/stack_package/cookiecutter.json

I think it's reasonable to start a stack package in the `lsst-sqre` org that eventually will migrate to the `lsst` org.

Add lsst-sqre to the list of github orgs

---

project_templates/technote_latex/CHANGELOG.md
project_templates/technote_latex/README.md
project_templates/technote_latex/cookiecutter.json
project_templates/technote_latex/templatekit.yaml
project_templates/technote_rst/CHANGELOG.md
project_templates/technote_rst/README.md
project_templates/technote_rst/cookiecutter.json
project_templates/technote_rst/templatekit.yaml

This series was requested by @tribeiro for the T&S group. They have opted to use the new lsst-tstn org rather than add technotes to their lsst-ts org.

Add TSTN technote series

---

project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/cookiecutter.json

Adds the `lsst-verification-and-validation` GitHub org to the `stack_package` configuration.

DM-21376: Add lsst-verification-and-validation org

---

project_templates/nbreport/CHANGELOG.md
project_templates/nbreport/EXAMPLE-000/nbreport.yaml
project_templates/nbreport/{{cookiecutter.handle}}/nbreport.yaml
project_templates/technote_rst/CHANGELOG.md
project_templates/technote_rst/cookiecutter.json
project_templates/technote_rst/testn-000/metadata.yaml
project_templates/technote_rst/{{cookiecutter.repo_name}}/metadata.yaml
requirements.txt

This PR updates the templates repository to use Templatekit 0.3.0+. This new version (see https://templatekit.lsst.io/changelog.html) includes a new `escape_yaml_doublequoted` Jinja filter. With this filter, in tandem with double-quoted YAML strings, we can support arbitrary string content in YAML files. No longer will our templates break with quotes, for instance.
This PR specifically updates the nbreport and technote_rst templates to use the new filter.

DM-21528: Ensure templated content in nbreport and technote_rst YAML files is escaped

---

.travis.yml
requirements.txt

- Use the new `templatekit check` command, available in templatekit 0.4.0. This command runs `scons` to regenerate examples, and then detect uncommitted state in the examples. The `templatekit check` command improves upon the previous testing strategy by also detecting untracked files. This can happen when a template is changed, but the template developer neglected to run `scons` locally and commit the resulting example. CI will now detect this.
- Also update Travis to Xenial and Python 3.7.

DM-21707: Detect untracked example files in CI

---

project_templates/technote_rst/CHANGELOG.md
project_templates/technote_rst/testn-000/requirements.txt
project_templates/technote_rst/{{cookiecutter.repo_name}}/requirements.txt

This keeps the reStructuredText technotes in step with the latest versions of Documenteer, but otherwise doesn't affect the user experience.
Documenteer 0.5.4 specifically solves a bug in the sidebar link for technotes.

DM-20839: Update technote_rst to documenteer 0.5 series

---

file_templates/copyright/COPYRIGHT
project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/example/COPYRIGHT
project_templates/stack_package/example/doc/lsst.example/index.rst
project_templates/stack_package/example_dataonly/COPYRIGHT
project_templates/stack_package/example_dds/COPYRIGHT
project_templates/stack_package/example_dds/doc/index.rst
project_templates/stack_package/example_pythononly/COPYRIGHT
project_templates/stack_package/example_pythononly/doc/lsst.example.pythononly/index.rst
project_templates/stack_package/example_standalone/COPYRIGHT
project_templates/stack_package/example_standalone/doc/index.rst
project_templates/stack_package/example_subpackage/COPYRIGHT
project_templates/stack_package/example_subpackage/doc/lsst.example.subpackage/index.rst
project_templates/stack_package/{{cookiecutter.package_name}}/doc/{{cookiecutter.python_module}}/index.rst
project_templates/technote_aastex/testn-000/COPYRIGHT
project_templates/technote_latex/testn-000/COPYRIGHT
project_templates/technote_rst/testn-000/COPYRIGHT
project_templates/technote_rst/testn-000/metadata.yaml

* Add `lsst-pipelinetask` to module documentation template
* Include automatic 2020 copyright updates.

DM-22520: Add lsst-pipelinetask to module documentation template

---

project_templates/roundtable_aiohttp_bot/example/pyproject.toml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/pyproject.toml

The setuptools-scm documentation says that setuptools 42 or later
is required to use tools.setuptools_scm in pyproject.toml.

Bump roundtable_aiohttp_bot setuptools dependency

---

project_templates/roundtable_aiohttp_bot/example/requirements/dev.in
project_templates/roundtable_aiohttp_bot/example/requirements/main.in
project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/requirements/dev.in
project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/requirements/main.in

In the roundtable_aiohttp_bot template, don't explicitly set
--index-url in the requirements templates.  This potentially makes
the template fragile against changes in PyPI.  The frozen SHA-256
hashes should be sufficient to ensure explicitness.

Remove explicit --index-url settings

---

project_templates/roundtable_aiohttp_bot/example/Dockerfile
project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/Dockerfile

The runtime-image build step does not run another script for
package installation.  Instead, all system packages should be
installed by scripts/install-base-packages.sh.  Update the
introductory comment accordingly.

Remove old roundtable_aiohttp_bot Dockerfile comment

---

project_templates/roundtable_aiohttp_bot/example/setup.cfg
project_templates/roundtable_aiohttp_bot/{{cookiecutter.repo_name}}/setup.cfg

This provides the specific error code that can be used in a
type: ignore comment to suppress only that error.  That isn't
useful yet because flake8 will complain about those comments, but
that will be fixed in the next flake8 release and there's no harm
in ensuring this configuration setting is present in newly-created
bots.

Enable show_error_codes for mypy

---

project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml

The sed expression was only replacing the first /, which is
insufficient for u/<username> branch naming conventions.

Replace all /'s in Docker tag for roundtable_aiohttp_bot

---

project_templates/roundtable_aiohttp_bot/example/setup.cfg
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/setup.cfg

packaging.python.org says that standard licenses should be
indicated primarily via trove classifiers and the license field is
optional and intended for custom non-standard licenses.  Omit it
and rely on the trove classifiers, which avoids the question of what
the valid values for this field are.
Reference: https://packaging.python.org/guides/distributing-packages-using-setuptools/#license

Remove license key from setup.cfg

---

project_templates/roundtable_aiohttp_bot/example/setup.cfg
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/setup.cfg

flake8 disagrees with PEP-8 in two places and black enforces the
PEP-8 formatting.  Add ignore rules in case they come up in any
packages.

[DM-23656] Add flake8 ignore for PEP-8 conflicts

---

project_templates/roundtable_aiohttp_bot/example/src/example/app.py
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/app.py

Two small things after running the safir bootstrap guide for my
new project, since I wanted to give it a shot!
It looks like the project name needs to be quoted as a string,
since the modulename isn't really imported or used there.  Quoting
seems to work.
After running black the first time, for some reason it really wants
there to be an extra comma after the keyword on its own line.  So I
figured it might be good to fix that just so there's not a lot of
reformatting going on in the first commit.

[DM-23913] Quoting and black reformatting

---

project_templates/technote_latex/CHANGELOG.md
project_templates/technote_latex/README.md
project_templates/technote_latex/cookiecutter.json
project_templates/technote_latex/templatekit.yaml
project_templates/technote_rst/CHANGELOG.md
project_templates/technote_rst/README.md
project_templates/technote_rst/cookiecutter.json
project_templates/technote_rst/templatekit.yaml

These technotes are hosted in the https://github.com/rubin-observatory GitHub organization.
The other half of this work is to add @sqrbot to the rubin-observatory organization to enable Slack-based project creation. @sqrbot requires `admin` level access.
This work resolves a request from @womullan.

DM-25056: Add support for the OPSTN technote series

---

project_templates/technote_latex/README.md
project_templates/technote_latex/cookiecutter.json
project_templates/technote_latex/templatekit.yaml
project_templates/technote_rst/README.md
project_templates/technote_rst/cookiecutter.json
project_templates/technote_rst/templatekit.yaml

The canonical name for this organization is now in lowercase.

Rename LSST-IT org to lsst-it

---

project_templates/technote_rst/testn-000/.github/workflows/ci.yaml
project_templates/technote_rst/{{cookiecutter.repo_name}}/.github/workflows/ci.yaml

- Add an env field to the `technote_rst` workflow's upload step to give it access to the LTD credentials stored as GitHub Secrets (already done for LaTeX technotes).
- Only upload specifically on a push event, not a PR event (which won't have access to credentials, and thus will fail.

DM-25233: Fix technote_rst usage of secrets in GitHub Actions

---

project_templates/technote_rst/testn-000/README.rst
project_templates/technote_rst/{{cookiecutter.repo_name}}/README.rst

This was accidentally left behind when the badge for GitHub Actions was added.

DM-25233: Drop the CI badge for Travis CI in rst technotes

---

project_templates/roundtable_aiohttp_bot/example/.github/dependabot.yml
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/example/.pre-commit-config.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/dependabot.yml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.pre-commit-config.yaml

- Update pre-commit hook dependencies to the latest version.
- Update GitHub workflows to the latest version.
- Add GitHub dependabot configuration for GitHub actions updates.
The pre-commit update is a one-off.  Eventually the best way to
handle this will be for sqrbot-jr to run neophile after generating
the template to update all of the versions before the first commit,
but that's not ready yet.

[DM-25183] Update dependencies in roundtable template

---

project_templates/roundtable_aiohttp_bot/example/src/example/cli.py
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/cli.py

Set info_name in the context before displaying help for subcommands.
Otherwise, the usage summary displayed as part of the help will show
"help" as the subcommand because it is the current context.

Fix usage information for subcommands

---

project_templates/latex_lsstdoc/cookiecutter.json
project_templates/latex_lsstdoc/templatekit.yaml

This is necessary for documents such as LDM.

Enable creation of lsstdoc docs in lsst org

---

project_templates/roundtable_aiohttp_bot/example/.github/dependabot.yml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/dependabot.yml

For the roundtable_aiohttp_bot tmeplate, add Docker monitoring to
the default Dependabot configuration.  This won't catch a lot, but
it will warn if the base Docker image is out of date.

[DM-25844] Add Docker monitoring to Dependabot config

---

project_templates/test_report/README.md
project_templates/test_report/cookiecutter.json
project_templates/test_report/templatekit.yaml

This adds support for SCTR test reports with `sqrbot-jr project create`, which uses the same infrastructure as DMTR reports.

DM-26975: Add support for SCTR test reports

---

.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/example/.pre-commit-config.yaml
project_templates/roundtable_aiohttp_bot/example/Dockerfile
project_templates/roundtable_aiohttp_bot/example/pyproject.toml
project_templates/roundtable_aiohttp_bot/example/scripts/install-dependency-packages.sh
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.pre-commit-config.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/Dockerfile
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/pyproject.toml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/install-base-packages.sh
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/install-dependency-packages.sh

Add a new script that installs packages required only in the
dependencies image and install build-essential by default, since
this is often required for building Python extensions, particularly
when upgrading to a new Python version.
Use a test matrix of Python 3.8 and 3.9 by default.  Stop pinning
the version in tox and use whatever the default Python version is.
Remove or update a few more references to Python 3.7.
Update pre-commit hook versions to the latest.
Use the `@v2` syntax for the GitHub Actions configuration, since all
the actions move the major version tag with each release.  This
avoids requiring updates for each minor release.

Update roundtable_aiohttp_bot template

---

project_templates/roundtable_aiohttp_bot/example/scripts/install-base-packages.sh
project_templates/roundtable_aiohttp_bot/example/scripts/install-dependency-packages.sh
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/install-base-packages.sh
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/install-dependency-packages.sh

The whole point of adding a separate install-dependency-packages
script was to not install build-essential in the base layer but
only where Python extensions were built.  Then I accidentally left
this in the base script.  Clean it up.
Also install libffi-dev in the dependency image since it's often needed
by cffi.

Stop installing build-essential in the base image

---

project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/roundtable_aiohttp_bot/example/manifests/base/deployment.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/manifests/base/deployment.yaml
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

Add security hardening to the template Kubernetes maniphest for
the Roundtable aiohttp bot.
This also picked up some month name changes to some templates.

[DM-28993] Add security configuration to aiohttp manifest

---

project_templates/roundtable_aiohttp_bot/example/.dockerignore
project_templates/roundtable_aiohttp_bot/example/.github/workflows/build.yaml
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/example/scripts/docker-tag.sh
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.dockerignore
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/docker-tag.sh

Use the official pre-commit action instead of running pre-commit
with tox, since it automatically handles caching.  Add the Python
version to the tox cache key and remove .pre-commit-config.yaml.
Change the Docker build to only trigger on ticket branches and
tags to cut down on the number of spurious images we push.  Use the
official Docker actions and cache layers in GitHub rather than on
Docker Hub.
Use an external script to determine the tag of the Docker image.

[DM-29123] Update CI and Docker builds

---

project_templates/test_report/TESTTR-0/TESTTR-0.tex
project_templates/test_report/TESTTR-0/history_and_info.tex
project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/history_and_info.tex
project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}.tex

Per agreement with Wil about a coordinated change in `docsteady`, use camelCase consistently
across all document categories for the `\vcsDate` and `\vcsRevision` macros.
Matches changes made in #102 to the generation of the `meta.tex` file.

DM-29442: Use camelCase consistently for \vcs* macros.

---

project_templates/stack_package/CHANGELOG.md
project_templates/stack_package/example/doc/conf.py
project_templates/stack_package/example/setup.cfg
project_templates/stack_package/example_dataonly/doc/conf.py
project_templates/stack_package/example_dds/doc/conf.py
project_templates/stack_package/example_dds/setup.cfg
project_templates/stack_package/example_pythononly/doc/conf.py
project_templates/stack_package/example_pythononly/setup.cfg
project_templates/stack_package/example_standalone/doc/conf.py
project_templates/stack_package/example_standalone/setup.cfg
project_templates/stack_package/example_subpackage/doc/conf.py
project_templates/stack_package/example_subpackage/setup.cfg
project_templates/stack_package/{{cookiecutter.package_name}}/doc/conf.py
project_templates/stack_package/{{cookiecutter.package_name}}/setup.cfg

This new configuration API is available in documenteer 0.6 and solves problems around recursion errors in the Sphinx build.

DM-29889: Update conf.py to documenteer.conf.pipelinespkg in stack_package template

---

file_templates/copyright/cookiecutter.json
project_templates/stack_package/cookiecutter.json

@womullan I think we should have done this in #105 already, it should be trivial to review. There's some work to do at the labs to enable lab staff to assert copyright in open source projects but that can be pursued in parallel to making it easy for staff to make a COPYRIGHT file, I think.

Tiny patch to extend stack package copyright holder list to include Fermilab and BNL, following #105

---

project_templates/technote_rst/CHANGELOG.md
project_templates/technote_rst/testn-000/.gitattributes
project_templates/technote_rst/testn-000/lsstbib/books.bib
project_templates/technote_rst/testn-000/lsstbib/lsst-dm.bib
project_templates/technote_rst/testn-000/lsstbib/lsst.bib
project_templates/technote_rst/testn-000/lsstbib/refs.bib
project_templates/technote_rst/testn-000/lsstbib/refs_ads.bib
project_templates/technote_rst/{{cookiecutter.repo_name}}/.gitattributes
project_templates/technote_rst/{{cookiecutter.repo_name}}/lsstbib/books.bib
project_templates/technote_rst/{{cookiecutter.repo_name}}/lsstbib/lsst-dm.bib
project_templates/technote_rst/{{cookiecutter.repo_name}}/lsstbib/lsst.bib
project_templates/technote_rst/{{cookiecutter.repo_name}}/lsstbib/refs.bib
project_templates/technote_rst/{{cookiecutter.repo_name}}/lsstbib/refs_ads.bib

The `.gitattributes` file now helps suppress the vendored bibtex files from [GitHub pull requests and linguist stats](https://docs.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github).

Add .gitattributes to rst technote template to suppress vendored bib files from GitHub stats/reviews

---

project_templates/fastapi_safir_app/example/.dockerignore
project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/example/Dockerfile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.dockerignore
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile

The version number was incorrectly set to a development working
version instead of the tagged version when building from a tag.
Fix this by including tags in the checkout so that setuptools_scm
can use them, not excluding any files from the Docker copy, and
using a separate working directory from the /app directory that's
used by the FastAPI image.

[DM-30907] Fix version number for FastAPI applications

---

project_templates/fastapi_safir_app/example/src/example/main.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/main.py
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

Rather than hard-coding the value from the template, pull it from
setup.cfg so that subsequent changes only have to be made in one
place.

[DM-31361] Use metadata for FastAPI app summary

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

Our previous approach of running CI workflows on push but not pull
request is fairly hostile to external contributors.  Enable
workflows for pull requests in the relevant templates.  We also
want to re-run CI workflows on tags and merges to master to confirm
nothing broke, so also enable push CI but exclude the branches we
use to create local pull requests to avoid running the CI workflow
twice and wasting some resources.
It's not a big deal if we run workflows twice occasionally, so this
list of exclusions doesn't need to be comprehensive.

[DM-31621] Update how workflows run

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/example/src/example/handlers/external.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/handlers/external.py
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml

The change to run CI workflows on pull requests and to avoid running
them on pushes to branches that will be pull requests broke running
the Docker build because github.ref is different for pull request
workflows.  Fix this by looking at the head_ref instead, to trigger
Docker builds for pull requests from ticket branches.
It's not entirely clear form the GitHub Actions documentation
whether having a branches_ignore key prevents running the action
on tags, so be explicit.

[DM-31621] Fix Docker builds on ticket branches

---

project_templates/fastapi_safir_app/example/LICENSE
project_templates/fastapi_safir_app/{{cookiecutter.name}}/LICENSE
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/handlers/external.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/handlers/internal.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/main.py
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/app.py
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

This PR makes a few small fixes/improvements to the aiohttp and FastAPI application templates:
1. Put the copyright entity on the same line as the copyright. This is a better default.
2. Change the argument to the metadata functions to use the name set in `setup.cfg`, rather than the package namespace. importlib uses the package name rather than the Python namespace (the naming of these variables makes it easy to confuse which variable is appropriate). This fix only affects packages that use a hyphen or underscore in their names.

Small fixes to the FastAPI and aiohttp package templates

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/example/scripts/docker-tag.sh
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/scripts/docker-tag.sh
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/example/scripts/docker-tag.sh
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/scripts/docker-tag.sh
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

In the roundtable_aiohttp_bot and fastapi_safir_app project
templates, fix the script to determine the Docker tag of a build
to work correctly with pull requests as well as pushes.  Add
Python 3.10 to the default test matrix for both app types.
In the roundtable_aiohttp_bot project template, set fetch-depth
to 0 when building Docker images (matching fastapi_safir_app) so
that setuptools_scm will generate correct version numbers.
Taken from @jonathansick's fixes for noteburst.

[DM-31621] Fix Docker tags for app workflows

---

project_templates/fastapi_safir_app/example/Dockerfile
project_templates/fastapi_safir_app/example/requirements/dev.in
project_templates/fastapi_safir_app/example/requirements/main.in
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/requirements/dev.in
project_templates/fastapi_safir_app/{{cookiecutter.name}}/requirements/main.in

For the fastapi_safir_app template, stop using the FastAPI Docker
image as a base since it's been deprecated upstream.  It uses
gunicorn to start a bunch of worker processes, which is unnecessary
in Kubernetes (one can just spawn more pods) and often not desired
for applications that use in-memory data structures and should only
run one copy.
Instead, base the Docker image on the normal Python base image and
run the application directly using uvicorn.  Remove gunicorn from
the default dependencies.

[DM-32556] Stop using FastAPI Docker image

---

project_templates/fastapi_safir_app/example/Makefile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Makefile
project_templates/roundtable_aiohttp_bot/example/Makefile
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/Makefile

I think this is a reasonable choice because the next command relies on pre-commit being installed. For example, a clean virtual environment may not have pre-commit installed yet, so we'd want to handle that for the developer.

Install pre-commit during make init

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/roundtable_aiohttp_bot/example/.github/workflows/ci.yaml
project_templates/roundtable_aiohttp_bot/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

Switch the caching for Docker builds to the new GitHub Actions
cache, and remove the workaround for the problems with the local
cache.
This was tested with vo-cutouts.

[DM-33719] Use new GitHub Action Docker build caching

---

project_templates/fastapi_safir_app/example/pyproject.toml
project_templates/fastapi_safir_app/example/tests/conftest.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/pyproject.toml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/tests/conftest.py
requirements.txt

Enable strict asyncio mode and mark the fixtures accordingly, to
support the latest pytest-asyncio.  Tell pytest that all Python
files under tests are tests, so that pytest will automatically
generate verbose diffs for failed asserts.
Tested by creating an example application and confirming that all
of its tests passed without warnings.

[DM-33604] Update pytest fixtures for fastapi_safir_app

---

.github/workflows/ci.yaml
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt
requirements.txt

Allow use of the new 0.5.0 version, and in general assume the
latest released version will work.
Remove the markupsafe pin, which is no longer needed since the
latest templatekit permits use of the latest Jinja2.

[DM-33981] Unpin templatekit

---

README.md
project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/example/Dockerfile
project_templates/fastapi_safir_app/example/setup.cfg
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/setup.cfg

Add Python 3.10 for new FastAPI projects, drop Python 3.8 support,
and set the default Docker image to use Python 3.10.  Keep 3.9 in
the matrix since it may be required for packages with a Kafka
dependency.

[DM-34075] Update FastAPI template for 3.10, drop 3.8

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml

Add the GitHub Container Registry as a default target for Docker
images for FastAPI Safir apps.

[DM-34075] Push FastAPI apps to GHCR by default

---

project_templates/fastapi_safir_app/example/tests/conftest.py
project_templates/fastapi_safir_app/example/tests/handlers/external_test.py
project_templates/fastapi_safir_app/example/tests/handlers/internal_test.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/tests/conftest.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/tests/handlers/external_test.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/tests/handlers/internal_test.py

Using this construct is optional in our code, but we're starting to
lean away from using it routinely since it can mask some errors.
The uses in the test suite of the FastAPI app are not significant
or necessary, so remove this construction there to not create a
confusing example.

[DM-34075] Stop using if TYPE_CHECKING in FastAPI template

---

project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/manifests/base/deployment.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/manifests/base/kustomization.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/config.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/handlers/external.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/handlers/internal.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/tests/handlers/external_test.py

In the Kustomization configuration for a FastAPI Safir app, default
to using the GitHub Container Registry as the source for the image
instead of Docker Hub.
Use the lowercased application name for the Docker image and the
default route instead of the Python package name.

[DM-34075] Pull FastAPI images from GHCR by default

---

project_templates/fastapi_safir_app/example/Makefile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Makefile

Add a new Makefile target update-deps-no-hashes that omits the
hashes from the generated dependencies.  This is useful when one
is testing against an unreleased dependency via Git and therefore
cannot generate hashes.

Add update-deps-no-hashes to FastAPI template

---

CONTRIBUTING.md
README.md
SConstruct
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/sitcom_personal_notebooks/README.md
project_templates/sitcom_personal_notebooks/SConscript
project_templates/sitcom_personal_notebooks/cookiecutter.json
project_templates/sitcom_personal_notebooks/notebooks_example/.gitignore
project_templates/sitcom_personal_notebooks/notebooks_example/COPYRIGHT
project_templates/sitcom_personal_notebooks/notebooks_example/LICENSE
project_templates/sitcom_personal_notebooks/notebooks_example/README.rst
project_templates/sitcom_personal_notebooks/notebooks_example/notebooks/summit/Example_Notebook.ipynb
project_templates/sitcom_personal_notebooks/notebooks_example/python/lsst/sitcom/example/example_function.py
project_templates/sitcom_personal_notebooks/notebooks_example/tests/test_method_example.py
project_templates/sitcom_personal_notebooks/notebooks_example/ups/notebooks_example.table
project_templates/sitcom_personal_notebooks/templatekit.yaml
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/.gitignore
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/COPYRIGHT
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/LICENSE
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/README.rst
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/notebooks/summit/Example_Notebook.ipynb
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/python/lsst/sitcom/{{cookiecutter.username}}/example_function.py
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/tests/test_method_example.py
project_templates/sitcom_personal_notebooks/{{cookiecutter.repo_name}}/ups/{{cookiecutter.repo_name}}.table
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

This template creates a personal notebooks repository for SIT-Com team members to store and organize notebooks and any associated methods which contain Rubin-related work but are not meant for public consumption and are not expected to be supported by the author. The reason for creation of these repos is to ensure work is documented and stored in a place that is available by all SIT-Com personnel. This is important to ensure content is available to others in the event that the original author cannot support the activity.
The archetype for this template is https://github.com/lsst-sitcom/notebooks_pingraham

DM-34274: Add SIT-Com personal notebook repository template

---

project_templates/sitcom_personal_notebooks/cookiecutter.json
project_templates/sitcom_personal_notebooks/templatekit.yaml

At the moment templatebot-aide requires a github_org be present in the
dialog, even if there isn't a choice (it's not getting the variable from
cookiecutter.json at this stage).

DM-34274: Add github_org to dialog fields

---

project_templates/technote_rst/testn-000/.github/dependabot.yml
project_templates/technote_rst/testn-000/.github/workflows/ci.yaml
project_templates/technote_rst/testn-000/conf.py
project_templates/technote_rst/testn-000/index.rst
project_templates/technote_rst/testn-000/requirements.txt
project_templates/technote_rst/{{cookiecutter.repo_name}}/.github/dependabot.yml
project_templates/technote_rst/{{cookiecutter.repo_name}}/.github/workflows/ci.yaml
project_templates/technote_rst/{{cookiecutter.repo_name}}/conf.py
project_templates/technote_rst/{{cookiecutter.repo_name}}/index.rst
project_templates/technote_rst/{{cookiecutter.repo_name}}/requirements.txt

- Adopt the [new conf.py API](https://documenteer.lsst.io/technotes/configuration.html) available in documenteer 0.6
- Unpin documenteer to start using documenteer 0.6
- Simplify the starter text
- Adopt reusable workflows to streamline GitHub Actions, see https://github.com/lsst-sqre/rubin-sphinx-technote-workflows/pull/1

DM-34231: Update reStructuredText technote template for documenteer 0.6+

---

project_templates/fastapi_safir_app/example/src/example/main.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/main.py
project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/test_report/TESTTR-0/bibentry.txt

The current mypy plus typeshed plus the Python 3.10 core library
has a bug causing mypy to not think get is a valid method on the
return value of importlib.metadata.metadata because it returns a
Protocol that doesn't implement get.  I've filed a issue in case
this is not intended (https://github.com/python/typeshed/issues/7767),
but we know that any package created by this template will always
have Summary and Version metadata, so we can use them
unconditionally.
Previously, this may not have worked in situations where the
package was being used uninstalled, but since we now do everything
including local development servers from inside tox, and make init
also installs the package for running pytest directly, this should
no longer be an issue.  setuptools_scm should always generate a …

Avoid get on PackageMetadata in FastAPI template

---

project_templates/technote_rst/testn-000/Makefile
project_templates/technote_rst/{{cookiecutter.repo_name}}/Makefile

I keep finding missing cross-references or syntax errors in rendered
tech note branches because I don't think to run make html locally to
check for errors and the GitHub Actions workflow ignores them.  Change
the default Sphinx arguments to make warnings fatal, on the grounds
that all Sphinx warnings seem to be avoidable (with an exclusion if
nothing else) and it's better to catch these automatically rather
than requiring human proofreading.

[DM-35179] Make warnings fatal in rST tech notes

---

project_templates/square_pypi_package/example/.github/workflows/ci.yaml
project_templates/square_pypi_package/example/.github/workflows/periodic-ci.yaml
project_templates/square_pypi_package/{{cookiecutter.pypi_name}}/.github/workflows/ci.yaml
project_templates/square_pypi_package/{{cookiecutter.pypi_name}}/.github/workflows/periodic-ci.yaml

The [lsst-sqre/build-and-publish-to-pypi](https://github.com/lsst-sqre/build-and-publish-to-pypi) action has an upload input that allows us to disable uploads in certain circumstances. This lets us run the action in a dry-run mode for PR and the weekly CI to validate that the packaging works.
This has been implemented in https://github.com/lsst-sqre/kafkit already.

DM-35448: Enable dry runs of builds for PyPI

---

project_templates/technote_latex/testn-000/.gitignore
project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.gitignore

This file is produced as a byproduct of xelatex. The other tex-based templates already ignore this file; this must have been missed when we switched from pdflatex to xelatex.

DM-35808: Add *.xdv to technote_latex gitignore

---

project_templates/latex_lsstdoc/EXAMPLE-0/bibentry.txt
project_templates/latex_lsstdoc/EXAMPLE/bibentry.txt
project_templates/latex_lsstdoc/{{cookiecutter.handle}}/bibentry.txt
project_templates/technote_rst/testn-000/bibentry.txt
project_templates/technote_rst/{{cookiecutter.repo_name}}/bibentry.txt

Now that the lsst-texmf bib files are being automatically updated based on metadata extracted by Ook and hosted out of Algolia, there's no need for these bibentry files. Besides, that, these embedded bibentry files create monthly churn in the examples, and become quickly outdated in the documents they're injected into.

DM-35809: Drop bibtentry.txt files

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml

Use the new lsst-sqre/run-tox GitHub Action and separate lint into
a separate run, following the setup for square_pypi_package.

[DM-28121] Update FastAPI GitHub Actions configuration

---

project_templates/technote_latex/testn-000/bibentry.txt
project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/bibentry.txt
project_templates/test_report/TESTTR-0/.github/workflows/docgen_from_Jira.yaml
project_templates/test_report/TESTTR-0/bibentry.txt
project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/.github/workflows/docgen_from_Jira.yaml
project_templates/test_report/{{cookiecutter.series.upper()}}-{{cookiecutter.serial_number}}/bibentry.txt

- Fix capitalization of the --extra-download option in the Jira workflow
- Drop bibentry.txt since it's replaced by lsst-texmf's automatic bib file maintenance

DM-36197: Minor fixes for test-report template

---

project_templates/square_pypi_package/example/.github/workflows/ci.yaml
project_templates/square_pypi_package/example/docs/api.rst
project_templates/square_pypi_package/example/docs/dev/development.rst
project_templates/square_pypi_package/example/docs/dev/release.rst
project_templates/square_pypi_package/example/src/example/__init__.py
project_templates/square_pypi_package/example/tests/version_test.py
project_templates/square_pypi_package/example/tox.ini
project_templates/square_pypi_package/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/square_pypi_package/{{cookiecutter.name}}/docs/api.rst
project_templates/square_pypi_package/{{cookiecutter.name}}/docs/dev/development.rst
project_templates/square_pypi_package/{{cookiecutter.name}}/docs/dev/release.rst
project_templates/square_pypi_package/{{cookiecutter.name}}/src/{{cookiecutter.module_name}}/__init__.py
project_templates/square_pypi_package/{{cookiecutter.name}}/tests/version_test.py
project_templates/square_pypi_package/{{cookiecutter.name}}/tox.ini

- Fix some syntax and whitespace issues we found in the first run
- Add a simple test module so that pytest will run on the first commit
- Don't initially use docs-linkcheck in GitHub Actions because the project's own docs and PyPI package won't be available yet.

DM-36681: Improve the first-run experience of square_pypi_package

---

project_templates/technote_aastex/testn-000/.github/workflows/ci.yaml
project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
project_templates/technote_adasstex/testn-000/.github/workflows/ci.yaml
project_templates/technote_adasstex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
project_templates/technote_latex/testn-000/.github/workflows/ci.yaml
project_templates/technote_latex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
project_templates/technote_spietex/testn-000/.github/workflows/ci.yaml
project_templates/technote_spietex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml

These GitHub Actions workflows were missing from the initial template introductions.
Also update the actions in all tex-based document templates.
Finally, stop using the Lander v1 `--lsstdoc` option in non-lsstdoc document templates. The --lsstdoc option in lander v1 wasn't intended to be used for other LaTeX document classes, and although it works sometimes, it can fail. Let's try setting core metadata, the title and handle, manually. We'll return to this with Lander v2 where we can either set metadata in a file, or introduce specific tex parsers for SPIE, ADASS, and AASTeX documents.

DM-36698: Add GitHub Actions workflows to SPIE and ADASS documents

---

project_templates/technote_aastex/testn-000/.github/workflows/ci.yaml
project_templates/technote_aastex/testn-000/README.rst
project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
project_templates/technote_aastex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/README.rst
project_templates/technote_adasstex/testn-000/.github/workflows/ci.yaml
project_templates/technote_adasstex/testn-000/README.rst
project_templates/technote_adasstex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
project_templates/technote_adasstex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/README.rst
project_templates/technote_spietex/testn-000/.github/workflows/ci.yaml
project_templates/technote_spietex/testn-000/README.rst
project_templates/technote_spietex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/.github/workflows/ci.yaml
project_templates/technote_spietex/{{cookiecutter.series.lower()}}-{{cookiecutter.serial_number}}/README.rst

- Reverts the move to drop the lander `--lsstdoc` usage from #186. Although its not really correct, these templates do add Rubin lsstdoc-specific metadata macros that potentially lander v1 can pick up. Again, this will get resolved in Lander v2.
- Updates the README templates in these documents to point to GitHub Actions, rather than Travis CI, for the CI badge.

DM-36698: Fixes for SPIE, ADASS, and AASTeX technote templates

---

project_templates/fastapi_safir_app/example/.pre-commit-config.yaml
project_templates/fastapi_safir_app/example/Dockerfile
project_templates/fastapi_safir_app/example/requirements/main.in
project_templates/fastapi_safir_app/example/src/example/config.py
project_templates/fastapi_safir_app/example/src/example/main.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.pre-commit-config.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/requirements/main.in
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/config.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.package_name}}/main.py

Use pydantic.BaseSettings instead of a dataclass to construct the configuration for a FastAPI Safir app.  Use the new enums from Safir to validate the profile and log_level settings.

DM-37046: Switch to pydantic.BaseSettings for FastAPI config

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/example/.pre-commit-config.yaml
project_templates/fastapi_safir_app/example/Dockerfile
project_templates/fastapi_safir_app/example/pyproject.toml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.pre-commit-config.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Dockerfile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/pyproject.toml

Adopt various updates that we've been making to the projects generated by this template, on the grounds that new projects should default to the latest and greatest configuration.
- Require Python 3.11, update the default Dockerfile accordingly, and don't test against older versions.  If older version support is needed, it can always be re-added.
- Stop pushing containers to Docker Hub by default.  We now use GitHub Artifact Registry as the sole source of containers for many services, and this seems a better default for new packages.
- Enable showing the error code in mypy errors.  This is helpful if one needs to add an override.
- Update .pre-commit-config.yaml to the latest versions.

Update FastAPI project template

---

project_templates/fastapi_safir_app/example/Makefile
project_templates/fastapi_safir_app/example/src/example/__init__.py
project_templates/fastapi_safir_app/example/tox.ini
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Makefile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.module_name}}/__init__.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/tox.ini

- Use package name instead of `__name__` to derive `__version__` in top-level `__init__.py`
- `run` tox target collides with tox run subcommand; invoke as `tox -e=run` from Makefile to workaround this
- `setup.py` seems to have been removed from the template; remove from `mypy` invocation

A few small fastapi_safir_app template fixes

---

project_templates/fastapi_safir_app/example/requirements/dev.in
project_templates/fastapi_safir_app/example/requirements/main.in
project_templates/fastapi_safir_app/{{cookiecutter.name}}/requirements/dev.in
project_templates/fastapi_safir_app/{{cookiecutter.name}}/requirements/main.in

This makes editing them in Emacs a bit easier since it will then autorecognize comments and whatnot.

DM-37637: Mark requirements files as conf files for Emacs

---

project_templates/fastapi_safir_app/example/.dockerignore
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.dockerignore

This was added to jupyterlab-controller, but it seems like a good idea everywhere, so add it to the fastapi_safir_app.

DM-37933: Add .vscode to .dockerignore

---

project_templates/fastapi_safir_app/example/pyproject.toml
project_templates/fastapi_safir_app/example/requirements/dev.in
project_templates/fastapi_safir_app/{{cookiecutter.name}}/pyproject.toml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/requirements/dev.in

This plugin offers better type checking and handles some edge cases more correctly, and all FastAPI apps are going to be using Pydantic so there's no reason not to enable it. Enable all the strict checking options; they all seem useful and haven't caused me problems in Gafaelfawr or the lab controller.

DM-38170: Enable pydantic mypy plugin in fastapi_safir_app

---

project_templates/fastapi_safir_app/example/Makefile
project_templates/fastapi_safir_app/{{cookiecutter.name}}/Makefile

When rebuilding dependencies for a FastAPI Safir app, use the new backtracking pip-tools resolver. This suppresses a warning from pip-tools. I've been using this with several packages for a while without any trouble.

DM-38526: Use the backtracking pip-tools resolver

---

project_templates/fastapi_safir_app/example/src/example/config.py
project_templates/fastapi_safir_app/example/src/example/main.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/README.md
project_templates/fastapi_safir_app/{{cookiecutter.name}}/pyproject.toml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.module_name}}/config.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.module_name}}/main.py

Several of our applications have wanted to be able to override the base URL of the application (to test a parallel installation, for example), and while this was supported via overriding the package name, that approach is limited. (For instance, it's awkward to use that to configure a multipart path prefix such as /api/example.)
Follow times-square and jupyterlab-controller and add a path_prefix configuration option and environment variable to explicitly set the prefix.
Fix a few places where the potentially-uppercase package name was used in command-line entry points or URLs instead of the lowercased version.

DM-38526: Add path_prefix support to FastAPI template

---

project_templates/square_pypi_package/example/.github/workflows/ci.yaml
project_templates/square_pypi_package/example/pyproject.toml
project_templates/square_pypi_package/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/square_pypi_package/{{cookiecutter.name}}/pyproject.toml

Safir will soon require Python 3.11 or later, so do the same thing for square_pypi_package by default.

DM-38414: Bump Python version for square_pypi_package

---

project_templates/fastapi_safir_app/example/.pre-commit-config.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.pre-commit-config.yaml
project_templates/square_pypi_package/example/.pre-commit-config.yaml
project_templates/square_pypi_package/{{cookiecutter.name}}/.pre-commit-config.yaml

Normally developers will maintain pre-commit hooks either through neophile or on their own with `pre-commit autoupdate`, but older versions of the isort hook have a particular issue with poetry that makes the first-run experience more confusing.

DM-38757: Refresh pre-commit hooks

---

project_templates/fastapi_safir_app/example/src/example/main.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/src/{{cookiecutter.module_name}}/main.py

The way external routes were being mounted in the FastAPI app template introduced an extraneous extra slash in front of the URL, which is significant and thus broke the default test suite (and would break other expectations). Drop the extra slash.

DM-38757: Fix duplicate root "/" in external routes of FastAPI template

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/square_pypi_package/example/.github/workflows/ci.yaml
project_templates/square_pypi_package/example/.github/workflows/periodic-ci.yaml
project_templates/square_pypi_package/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/square_pypi_package/{{cookiecutter.name}}/.github/workflows/periodic-ci.yaml

For the default GitHub Actions CI jobs for fastapi_safir_app and square_pypi_package, add a timeout of 5 minutes for linting and 10 minutes for everything else. Nearly all of our packages are small and should complete much faster than that, and the larger ones can increase the timeout. The default GitHub Actions timeout is very long, which delays receiving the failure message when something has gone wrong.
Change the periodic CI job for square_pypi_package to require and only test Python 3.11, matching the default CI job.

DM-38425: Add timeouts to CI jobs

---

requirements.txt

We're doing this temporarily to continue support for the jinja2_time extension used by our templates.
See https://github.com/cookiecutter/cookiecutter/pull/1779
The next step of this resolution is to update templatebot and the templates here in concert to adopt the new inlined time extension available in cookiecutter 2.2+.

DM-39948: Pin cookiecutter < 2.2

---

project_templates/fastapi_safir_app/example/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/example/.github/workflows/dependencies.yaml
project_templates/fastapi_safir_app/example/.github/workflows/periodic-ci.yaml
project_templates/fastapi_safir_app/hooks/post_gen_project.py
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/ci.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/dependencies.yaml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/.github/workflows/periodic-ci.yaml
project_templates/square_pypi_package/example/.github/workflows/dependencies.yaml
project_templates/square_pypi_package/hooks/post_gen_project.py
project_templates/square_pypi_package/{{cookiecutter.name}}/.github/workflows/dependencies.yaml

Add support for neophile to both the fastapi_safir_app and square_pypi_package project templates.
For FastAPI apps with frozen dependencies, this means running neophile as a separate CI check on each pull request, running a periodic CI check that runs neophile and then the test suite, and adding a periodic GitHub Actions workflow to create a PR to update pre-commit dependencies.
For SQuaRE PyPI packages, this means running only the periodic workflow to create a PR to update pre-commit dependencies, since the other two steps are related to frozen dependencies.
If the created package is in lsst-sqre, report failures of the periodic GitHub Actions workflows to Slack.

DM-39989: Add neophile support to project templates

---

project_templates/square_pypi_package/example/pyproject.toml
project_templates/square_pypi_package/{{cookiecutter.name}}/pyproject.toml
project_templates/technote_rst/testn-000/.github/dependabot.yml
project_templates/technote_rst/testn-000/requirements.txt
project_templates/technote_rst/{{cookiecutter.repo_name}}/.github/dependabot.yml
project_templates/technote_rst/{{cookiecutter.repo_name}}/requirements.txt

Pin documenteer to <1 for square_pypi_project and technote_rst so that we have more intentional control over when we move to newer versions of the documentation stack. Add dependabot configuration for PyPI dependencies to technote_rst so that dependabot will create PRs to move to newer versions of documenteer.

DM-40059: Pin documenteer, add dependabot configuration

---

project_templates/fastapi_safir_app/example/pyproject.toml
project_templates/fastapi_safir_app/{{cookiecutter.name}}/pyproject.toml
project_templates/square_pypi_package/example/pyproject.toml
project_templates/square_pypi_package/{{cookiecutter.name}}/pyproject.toml

We're not yet ready to switch to Ruff by default for linting, but add our current Ruff configuration to the templates to make it easy to do so for those who want to. Sort the pyproject.toml tool.* configurations to put build system stuff first and then all testing and linting tools in alphabetical order.

DM-40567: Add Ruff configuration to project templates

---

project_templates/square_pypi_package/example/Makefile
project_templates/square_pypi_package/example/tox.ini
project_templates/square_pypi_package/{{cookiecutter.name}}/Makefile
project_templates/square_pypi_package/{{cookiecutter.name}}/tox.ini

Sphinx linkcheck doesn't produce a summary of failed links, but it does write one to output.txt. Move the linkcheck command into the Makefile so that we can use shell trickery to display the contents of that file on failure.
Add a help target as the default target in Makefile.

DM-40495: Better error reporting from Sphinx linkcheck

---

project_templates/technote_adasstex/cookiecutter.json
project_templates/technote_adasstex/templatekit.yaml
project_templates/technote_md_early_adopter/testn-000/.pre-commit-config.yaml
project_templates/technote_md_early_adopter/testn-000/technote.toml
project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/.pre-commit-config.yaml
project_templates/technote_rst_early_adopter/testn-000/.pre-commit-config.yaml
project_templates/technote_rst_early_adopter/testn-000/technote.toml
project_templates/technote_rst_early_adopter/{{cookiecutter.repo_name}}/.pre-commit-config.yaml

- In the early-adopter MD and rst technotes, comment out the trailing whitespace pre-commit hook to make it opt-in (@frossie)
- In the ADASS template, add SQR as a eligible series.

DM-41517: Minor updates to early-adopter technote templates and SQR for ADASS

---

project_templates/technote_md_early_adopter/SConscript
project_templates/technote_md_early_adopter/cookiecutter.json
project_templates/technote_md_early_adopter/templatekit.yaml
project_templates/technote_md_early_adopter/testn-000/technote.toml
project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/technote.toml
project_templates/technote_rst_early_adopter/SConscript
project_templates/technote_rst_early_adopter/cookiecutter.json
project_templates/technote_rst_early_adopter/templatekit.yaml
project_templates/technote_rst_early_adopter/testn-000/technote.toml
project_templates/technote_rst_early_adopter/{{cookiecutter.repo_name}}/technote.toml

The rst and md-formatted Sphinx technotes now use the author ID to correspond with the authodb.yaml file in github.com/lsst/lsst-texmf. This allows us to add more structured metadata about authors that is necessary for crosswalking to bibliographic schemas like Zenodo or CITATION.cff.
Other changes in technote.toml templating:
- add the organization field to technote.toml
- record `date_created` as a native TOML date-time, rather than a string.

DM-41781: Update author metadata in technotes

---

project_templates/technote_md_early_adopter/testn-000/Makefile
project_templates/technote_md_early_adopter/testn-000/technote.toml
project_templates/technote_md_early_adopter/testn-000/tox.ini
project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/Makefile
project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/tox.ini
project_templates/technote_rst_early_adopter/testn-000/Makefile
project_templates/technote_rst_early_adopter/testn-000/technote.toml
project_templates/technote_rst_early_adopter/testn-000/tox.ini
project_templates/technote_rst_early_adopter/{{cookiecutter.repo_name}}/Makefile
project_templates/technote_rst_early_adopter/{{cookiecutter.repo_name}}/tox.ini

These tox environments and corresponding make targets make it possible to run these documenteer commands through the isolated tox environment.

DM-42140: Add the add-author and sync-authors commands to technote tox envs

---

project_templates/technote_md_early_adopter/testn-000/technote.toml
project_templates/technote_md_early_adopter/{{cookiecutter.repo_name}}/technote.toml
project_templates/technote_rst_early_adopter/testn-000/technote.toml
project_templates/technote_rst_early_adopter/{{cookiecutter.repo_name}}/technote.toml

This metadata corresponds to the existing LICENSE files

DM-42144: Add license.id fields to technote.toml files in early-adopter technote templates

---

project_templates/technote_md/testn-000/technote.toml
project_templates/technote_md/{{cookiecutter.repo_name}}/technote.toml
project_templates/technote_rst/testn-000/technote.toml
project_templates/technote_rst/{{cookiecutter.repo_name}}/technote.toml

The "%-" operator was actually deleting the newline of the previous line too and putting e.g. orcid on the same line as `name.family`. This behaviour didn't show up in testing. We'll revert that and instead just leave the blank line.

DM-42586: Fix whitespace issues in conditional ORCiD

---

project_templates/technote_aastex/cookiecutter.json
project_templates/technote_aastex/templatekit.yaml
project_templates/technote_adasstex/cookiecutter.json
project_templates/technote_adasstex/templatekit.yaml
project_templates/technote_spietex/cookiecutter.json
project_templates/technote_spietex/templatekit.yaml

Now we can create proceedings for SPIE and ADASS and write for AAS journals as an RTN (Rubin technote) document, rather than a subsystem technote.

Add RTN support for SPIE, ADASS, AASTeX templates

---

project_templates/fastapi_safir_app/hooks/post_gen_project.py

The `depenendency.yaml` workflow was removed a while ago, so we shouldn't try to remove it. This affects non-lsst-sqre projects.

Drop dependency workflow removal hook

---

project_templates/technote_aastex/cookiecutter.json
project_templates/technote_aastex/templatekit.yaml
project_templates/technote_adasstex/cookiecutter.json
project_templates/technote_ascomtex/cookiecutter.json
project_templates/technote_ascomtex/templatekit.yaml

This fixes a situation we ran into for TSTN-050 where the `lsst-tstn` org was not in the cookiecutter.json for the technote_ascomtex template. While I'm at it, I also added SQR to the ASCOMTeX and ADASSTeX templates.

DM-49410: Update github orgs for ASCOMTeX and ADASSTeX templates
